name: Docker Image CI

on: [push]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@master
    - name: Build the Docker image
      with:
        actions_token: ${{ secrets.actions_token }}
      run: docker build --build-arg ${ACTIONS_TOKEN} . --file Dockerfile --tag github-runner:$(date +%s)
